/*
 * Created on 2017-01-24 ( Date ISO 2017-01-24 - Time 10:40:09 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.persistence;

import java.io.IOException;
import java.util.List;

import org.codehaus.jackson.JsonGenerationException;
import org.codehaus.jackson.JsonParseException;
import org.codehaus.jackson.map.JsonMappingException;
import org.demo.data.record.CarRecord;

/**
 * Persistence Interface for CarRecord.
 */
public interface CarPersistence { 

	/**
	 * Tries to find an entity using its Id / Primary Key
	 * @param id
	 * @return entity
	 * @throws IOException 
	 * @throws JsonMappingException 
	 * @throws JsonParseException 
	 */
	CarRecord findById( Integer id  ) throws JsonParseException, JsonMappingException, IOException ;

	/**
	 * Finds all entities.
	 * @return all entities
	 * @throws IOException 
	 * @throws JsonMappingException 
	 * @throws JsonParseException 
	 */
	List<CarRecord> findAll() throws JsonParseException, JsonMappingException, IOException;

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 * @throws IOException 
	 * @throws JsonMappingException 
	 * @throws JsonGenerationException 
	 */
	CarRecord save(CarRecord entity) throws JsonGenerationException, JsonMappingException, IOException;

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return true if the entity has been updated, false if not found and not updated
	 * @throws IOException 
	 * @throws JsonMappingException 
	 * @throws JsonGenerationException 
	 */
	boolean update(CarRecord entity) throws JsonGenerationException, JsonMappingException, IOException;

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 * @throws IOException 
	 * @throws JsonMappingException 
	 * @throws JsonGenerationException 
	 */
	CarRecord create(CarRecord entity) throws JsonGenerationException, JsonMappingException, IOException;

	/**
	 * Deletes an entity using its Id / Primary Key
	 * @param id
	 * @return true if the entity has been deleted, false if not found and not deleted
	 */
	boolean deleteById( Integer id );

	/**
	 * Deletes an entity using the Id / Primary Key stored in the given object
	 * @param the entity to be deleted (supposed to have a valid Id/PK )
	 * @return true if the entity has been deleted, false if not found and not deleted
	 */
	boolean delete( CarRecord entity );

}
