package dao;

import java.io.IOException;

/*
 * Created on 2017-01-24 ( Date ISO 2017-01-24 - Time 10:40:09 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */


import java.util.List;

import org.codehaus.jackson.JsonGenerationException;
import org.codehaus.jackson.JsonParseException;
import org.codehaus.jackson.map.JsonMappingException;

import bean.Car;

/**
 * Persistence Interface for Car.
 */
public interface CarPersistence { 

	/**
	 * Tries to find an entity using its Id / Primary Key
	 * @param id
	 * @return entity
	 * @throws IOException 
	 * @throws JsonMappingException 
	 * @throws JsonParseException 
	 */
	Car findById( Integer id  ) throws JsonParseException, JsonMappingException, IOException ;

	/**
	 * Finds all entities.
	 * @return all entities
	 * @throws IOException 
	 * @throws JsonMappingException 
	 * @throws JsonParseException 
	 */
	List<Car> findAll() throws JsonParseException, JsonMappingException, IOException;

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 * @throws IOException 
	 * @throws JsonMappingException 
	 * @throws JsonGenerationException 
	 */
	Car save(Car entity) throws JsonGenerationException, JsonMappingException, IOException;

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return true if the entity has been updated, false if not found and not updated
	 */
	boolean update(Car entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 * @throws IOException 
	 * @throws JsonMappingException 
	 * @throws JsonGenerationException 
	 */
	Car create(Car entity) throws JsonGenerationException, JsonMappingException, IOException;

	/**
	 * Deletes an entity using its Id / Primary Key
	 * @param id
	 * @return true if the entity has been deleted, false if not found and not deleted
	 * @throws IOException 
	 * @throws JsonParseException 
	 * @throws JsonMappingException 
	 * @throws JsonGenerationException 
	 */
	boolean deleteById( Integer id ) throws JsonGenerationException, JsonMappingException, JsonParseException, IOException;

	/**
	 * Deletes an entity using the Id / Primary Key stored in the given object
	 * @param the entity to be deleted (supposed to have a valid Id/PK )
	 * @return true if the entity has been deleted, false if not found and not deleted
	 */
	boolean delete( Car entity );

}
