/*
 * Created on 2017-02-10 ( Date ISO 2017-02-10 - Time 11:16:38 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.persistence.impl.redis;

import java.util.List;

import javax.inject.Named;

import org.demo.data.record.CarRecord;
import org.demo.persistence.CarPersistence;
import org.demo.persistence.impl.redis.commons.GenericDAO;

@Named("CarPersistence")
public class CarPersistenceRedis extends GenericDAO<CarRecord> implements CarPersistence {

	private final static String SELECT_ALL = "car:*";
	private final static String entity = "car";

	// ----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public CarPersistenceRedis() {
		super();
	}

	// ---------------------------------------------------------------
	/**
	 * Creates a new instance of the bean and populates it with the given
	 * primary value(s)
	 * 
	 * @param id;
	 * @return the new instance
	 */

	@Override
	protected String getSetValuesForId(CarRecord bean) {
		// TODO Auto-generated method stub
		if (bean != null) {
			return "car:" + bean.getId();
		}
		return "";
	}

	/**
	 * Creates a new instance of the bean and populates it with the given
	 * primary value(s)
	 * 
	 * @param id;
	 * @return the new instance
	 */
	private CarRecord newInstanceWithPrimaryKey(Integer id) {
		CarRecord car = new CarRecord();
		car.setId(id);
		return car;
	}

	@Override
	protected CarRecord newInstance() {
		return new CarRecord();
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see interface
	 */
	@Override
	public CarRecord findById(Integer id) {
		CarRecord car = newInstanceWithPrimaryKey(id);

		return super.doSelect(car);
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see interface
	 */
	@Override
	public List<CarRecord> findAll() {

		return super.doSelectAll();
	}

	// ----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s)
	 * in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from
	 * the database<br>
	 * If not found, the given instance remains unchanged
	 */
	public CarRecord load(CarRecord car) {
		return super.doSelect(car);
	}

	// ----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database
	 * 
	 */
	public boolean insert(CarRecord car) {
		return super.doInsert(car);
	}

	// ----------------------------------------------------------------------
	/*
	 * (non-Javadoc)
	 * 
	 * @see interface
	 */
	@Override
	public CarRecord save(CarRecord car) {

		if (super.doExists(car)) {
			super.doUpdate(car);
		} else {
			insert(car);
		}
		return car;
	}

	// ----------------------------------------------------------------------
	/*
	 * (non-Javadoc)
	 * 
	 * @see interface
	 */
	@Override
	public boolean update(CarRecord car) {

		return super.doUpdate(car);
	}

	// ----------------------------------------------------------------------
	/*
	 * (non-Javadoc)
	 * 
	 * @see interface
	 */
	@Override
	public CarRecord create(CarRecord car) {

		insert(car);
		return car;
	}

	// ----------------------------------------------------------------------
	/*
	 * (non-Javadoc)
	 * 
	 * @see interface
	 */
	@Override
	public boolean deleteById(Integer id) {
		CarRecord car = newInstanceWithPrimaryKey(id);
		long r = super.doDelete(car);
		return r > 0L;
	}

	// ----------------------------------------------------------------------
	/*
	 * (non-Javadoc)
	 * 
	 * @see interface
	 */
	@Override
	public boolean delete(CarRecord car) {

		long r = super.doDelete(car);
		return r > 0L;
	}

	// ----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary
	 * key value(s)
	 * 
	 * @return
	 */
	// @Override
	public boolean exists(Integer id) {
		CarRecord car = newInstanceWithPrimaryKey(id);
		return super.doExists(car);
	}

	// ----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database
	 * 
	 * @return
	 */
	// @Override
	public boolean exists(CarRecord car) {
		return super.doExists(car);
	}

	// ----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database
	 * 
	 * @return
	 */
	// @Override
	public long count() {
		return super.doCountAll();
	}

	@Override
	protected String getSelectAll() {
		return SELECT_ALL;
	}

	@Override
	protected String getEntity() {
		return entity;
	}

	@Override
	protected void setBeanId(CarRecord car, Integer id) {
		car.setId((int) id);
	}

}
